  spring:
    datasource:
      url: jbdc:postgresql://localhost:5432/book_social_network
      username: username
      password: password
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQDialect
    mail:
      host: localhost
      port: 1025
      username: shem
      password: shem
      properties:
        mail:
          smtp:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
